### ISSUE TITLE
Cannot find module index.js

### ISSUE THREAD

**Issue by rajg2023** [rajivgiri513/TypeScript-NodeJS-VSCode#1]
$ npm start

> typescript_node@1.0.0 start
> tsc && ts-node ./dist/index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './index.js'
Require stack:
- G:\TypeScript Projects\typescript_node\dist\imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (C:\Users\rgiri\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:375:16)
    at getProjectSearchDir (C:\Users\rgiri\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:345:40)
    at main (C:\Users\rgiri\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:220:27)
    at Object.<anonymous> (C:\Users\rgiri\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:405:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'G:\\TypeScript Projects\\typescript_node\\dist\\imaginaryUncacheableRequireResolveScript'
  ]
}

**Comment by rajg2023** [comment]
Issue resolved by changing the relative path of the module.
