### ISSUE TITLE
Issue connecting to a servers in Mongo DB Cluster

### ISSUE THREAD

**Issue by rajg2023** [rajivgiri513/TypeScript-NodeJS-VSCode#2]
npm start

> typescript_node@1.0.0 start
> tsc && ts-node ./index.js

your server is running on port 3000
G:\TypeScript Projects\typescript_node\node_modules\mongoose\lib\connection.js:802
  const serverSelectionError = new ServerSelectionError();
                               ^
MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at NativeConnection.Connection.openUri (G:\TypeScript Projects\typescript_node\node_modules\mongoose\lib\connection.js:802:32)
    at G:\TypeScript Projects\typescript_node\node_modules\mongoose\lib\index.js:341:10
    at G:\TypeScript Projects\typescript_node\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (G:\TypeScript Projects\typescript_node\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (G:\TypeScript Projects\typescript_node\node_modules\mongoose\lib\index.js:1141:10)
    at Mongoose.connect (G:\TypeScript Projects\typescript_node\node_modules\mongoose\lib\index.js:340:20)
    at Object.<anonymous> (G:\TypeScript Projects\typescript_node\index.js:15:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'cluster0.q34li.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}

**Comment by rajg2023** [comment]
- [x] Testing and debugging in progress. 
- [x] Find the root cause of the issue.
- [x] Resolve the issue.
- [x] update the project.

**Comment by rajg2023** [comment]
Tested connection string using MongoDB compass; connected successfully.

**Comment by rajg2023** [comment]
Issue was with the function created to use the variables with the connection string. Resolved by using the mongoose.connect() method and original connection string URI, username and password from the Atlast/Cluster.
